package com.example.inventariosapp.domain.model.client

import com.example.inventariosapp.local.entity.ClientEntity
import com.google.gson.annotations.SerializedName

data class ClientResponseModel(
    @SerializedName("clienteId") var clienteId: Int? = null,
    @SerializedName("tipoPersonaId") val tipoPersonaId: Int? = null,
    @SerializedName("tipoPersona") val tipoPersona: String? = null,
    @SerializedName("tipoGiroId") val tipoGiroId: Int? = null,
    @SerializedName("tipoGiro") val tipoGiro: String? = null,
    @SerializedName("tipoPagoId") val tipoPagoId: Int? = null,
    @SerializedName("tipoPago") val tipoPago: String? = null,
    @SerializedName("nombreCliente") var nombreCliente: String? = null,
    @SerializedName("razonSocial") val razonSocial: String? = null,
    @SerializedName("rfc") val rfc: String? = null,
    @SerializedName("curp") val curp: String? = null,
    @SerializedName("paisId") val paisId: Int? = null,
    @SerializedName("estadoId") val estadoId: Int? = null,
    @SerializedName("ciudadId") val ciudadId: Int? = null,
    @SerializedName("localidad") val localidad: String? = null,
    @SerializedName("direccion") val direccion: String? = null,
    @SerializedName("colonia") val colonia: String? = null,
    @SerializedName("calle") val calle: String? = null,
    @SerializedName("codigoPostal") val codigoPostal: String? = null,
    @SerializedName("noExterior") val noExterior: String? = null,
    @SerializedName("noInterior") val noInterior: String? = null,
    @SerializedName("telefono") val telefono: String? = null,
    @SerializedName("correo") val correo: String? = null,
    @SerializedName("montoCredito") val montoCredito: Double? = null,
    @SerializedName("diasCredito") val diasCredito: Int? = null,
    @SerializedName("usuarioSesionId") val usuarioSesionId: Int? = null,
    @SerializedName("fechaIngreso") val fechaIngreso: String? = null,
    @SerializedName("fechaModifico") val fechaModifico: String? = null,
    @SerializedName("esActivo") val esActivo: Boolean? = null,
    @SerializedName("estatus") val estatus: String? = null
)

fun ClientResponseModel.toDb() = ClientEntity(
    clienteId = clienteId ?: 10000,
    tipoPersonaId = tipoPersonaId,
    tipoPersona = tipoPersona,
    tipoGiroId = tipoGiroId,
    tipoGiro = tipoGiro,
    tipoPagoId = tipoPagoId,
    tipoPago = tipoPago,
    nombreCliente = nombreCliente,
    razonSocial = razonSocial,
    rfc = rfc,
    curp = curp,
    paisId = paisId,
    estadoId = estadoId,
    ciudadId = ciudadId,
    localidad = localidad,
    direccion = direccion,
    colonia = colonia,
    calle = calle,
    codigoPostal = codigoPostal,
    noExterior = noExterior,
    noInterior = noInterior,
    telefono = telefono,
    correo = correo,
    montoCredito = montoCredito,
    diasCredito = diasCredito,
    usuarioSesionId = usuarioSesionId,
    fechaIngreso = fechaIngreso,
    fechaModifico = fechaModifico,
    esActivo = esActivo,
    estatus = estatus
)
