package com.example.appgeneric.domain.model

data class ClientModel(
    val clienteId: Int,
    val tipoPersonaId: Int?,
    val tipoPersona: String?,
    val tipoGiroId: Int?,
    val tipoGiro: String?,
    val tipoPagoId: Int?,
    val tipoPago: String?,
    val nombreCliente: String?,
    val razonSocial: String?,
    val rfc: String?,
    val curp: String?,
    val paisId: Int?,
    val estadoId: Int?,
    val ciudadId: Int?,
    val localidad: String?,
    val direccion: String?,
    val colonia: String?,
    val calle: String?,
    val codigoPostal: String?,
    val noExterior: String?,
    val noInterior: String?,
    val telefono: String?,
    val correo: String?,
    val montoCredito: Double?,
    val diasCredito: Int?,
    val usuarioSesionId: Int?,
    val fechaIngreso: String?,
    val fechaModifico: String?,
    val esActivo: Boolean?,
    val estatus: String?
)

fun ClientModel.toModel() = ClientModel(
    ciudadId!!,
    tipoPersonaId,
    tipoPersona,
    tipoGiroId,
    tipoGiro,
    tipoPagoId,
    tipoPago,
    nombreCliente,
    razonSocial,
    rfc,
    curp!!,
    paisId,
    estadoId,
    ciudadId,
    localidad,
    direccion,
    colonia,
    calle,
    codigoPostal,
    noExterior,
    noInterior,
    telefono,
    correo,
    montoCredito,
    diasCredito,
    usuarioSesionId,
    fechaIngreso,
    fechaModifico,
    esActivo,
    estatus
)
